#!/usr/bin/env python3
"""Sync theme JSON to CSS + Rust outputs."""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", SCRIPT_DIR.parent.parent))
THEME_DIR = PROJECT_ROOT / "packages" / "theme"
THEMES_JSON = THEME_DIR / "themes.json"
STATUS_JSON = THEME_DIR / "status-colors.json"
OUT_DIR = THEME_DIR / "generated"

# Token mappings: camelCase -> CSS custom property suffix
TOKEN_MAP = [
    ("bg", "bg"),
    ("surface", "surface"),
    ("surfaceAlt", "surface-alt"),
    ("accent", "accent"),
    ("accentSoft", "accent-soft"),
    ("text", "text"),
    ("textMuted", "text-muted"),
    ("border", "border"),
    ("gradient", "gradient"),
]

STATUS_MAP = [
    ("foreground", "foreground"),
    ("foregroundMuted", "foreground-muted"),
    ("success", "success"),
    ("successSoft", "success-soft"),
    ("error", "error"),
    ("errorSoft", "error-soft"),
    ("warning", "warning"),
    ("warningSoft", "warning-soft"),
    ("info", "info"),
]

FONT_MAP = [
    ("heading", "font-heading"),
    ("body", "font-body"),
    ("monoHeading", "font-mono-heading"),
    ("monoBody", "font-mono-body"),
]

DEFAULT_FONTS = {
    "heading": "'Inter', system-ui, sans-serif",
    "body": "'Inter', system-ui, sans-serif",
    "monoHeading": "'JetBrains Mono', 'Fira Code', monospace",
    "monoBody": "'JetBrains Mono', 'Fira Code', monospace",
}


def get_fonts(fonts: dict, theme_id: str) -> dict:
    """Get font config for a theme, falling back to default."""
    default = fonts.get("default", DEFAULT_FONTS)
    theme_fonts = fonts.get(theme_id, {})
    return {k: theme_fonts.get(k, default.get(k, DEFAULT_FONTS[k])) for k in DEFAULT_FONTS}


def css_vars(mode_obj: dict, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--adi-{prop}: {mode_obj[key]};" for key, prop in TOKEN_MAP)


def css_font_vars(font_obj: dict, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--adi-{prop}: {font_obj[key]};" for key, prop in FONT_MAP)


def css_status_vars(status: dict, mode_name: str, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--adi-{prop}: {status[mode_name][key]};" for key, prop in STATUS_MAP)


def generate_css(themes: dict, default_theme: str, fonts: dict, status: dict) -> str:
    """Generate CSS theme file."""
    lines = ["/* Generated by sync-theme — do not edit manually */", ""]

    default = themes[default_theme]
    default_font = get_fonts(fonts, default_theme)

    # Default theme (:root = dark)
    lines.append(f"/* ─── Default theme: {default_theme} (dark) ─── */")
    lines.append(":root {")
    lines.append(css_vars(default["dark"]))
    lines.append("")
    lines.append("  /* Fonts */")
    lines.append(css_font_vars(default_font))
    lines.append("")
    lines.append("  /* Status (universal) */")
    lines.append(css_status_vars(status, "dark"))
    lines.append("}")
    lines.append("")

    # Light mode for default theme
    lines.append("/* ─── Light mode ─── */")
    lines.append('[data-mode="light"], .light {')
    lines.append(css_vars(default["light"]))
    lines.append("")
    lines.append(css_status_vars(status, "light"))
    lines.append("}")
    lines.append("")

    # Auto light via system preference
    lines.append("/* Auto light via system preference */")
    lines.append("@media (prefers-color-scheme: light) {")
    lines.append('  :root:not([data-mode="dark"]):not(.dark) {')
    lines.append(css_vars(default["light"], "    "))
    lines.append("")
    lines.append(css_status_vars(status, "light", "    "))
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Per-theme overrides (skip default)
    for theme_id, theme in themes.items():
        if theme_id == default_theme:
            continue

        theme_font = get_fonts(fonts, theme_id)
        lines.append(f"/* ─── Theme: {theme_id} ─── */")

        # Dark (includes fonts)
        lines.append(f'[data-theme="{theme_id}"] {{')
        lines.append(css_vars(theme["dark"]))
        lines.append("")
        lines.append(css_font_vars(theme_font))
        lines.append("}")

        # Light
        lines.append(f'[data-theme="{theme_id}"][data-mode="light"],')
        lines.append(f'[data-theme="{theme_id}"].light {{')
        lines.append(css_vars(theme["light"]))
        lines.append("}")

        # Auto light
        lines.append("@media (prefers-color-scheme: light) {")
        lines.append(f'  [data-theme="{theme_id}"]:not([data-mode="dark"]):not(.dark) {{')
        lines.append(css_vars(theme["light"], "    "))
        lines.append("  }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


def rust_str(val: str) -> str:
    return f'"{val}"'


def generate_rust(themes: dict, default_theme: str, fonts: dict) -> str:
    """Generate Rust theme file."""
    lines = [
        "// Generated by sync-theme — do not edit manually",
        "",
        "pub struct ThemeFonts {",
        "    pub heading: &'static str,",
        "    pub body: &'static str,",
        "    pub mono_heading: &'static str,",
        "    pub mono_body: &'static str,",
        "}",
        "",
        "pub struct ThemeMode {",
        "    pub bg: &'static str,",
        "    pub surface: &'static str,",
        "    pub surface_alt: &'static str,",
        "    pub accent: &'static str,",
        "    pub accent_soft: &'static str,",
        "    pub text: &'static str,",
        "    pub text_muted: &'static str,",
        "    pub border: &'static str,",
        "    pub gradient: &'static str,",
        "}",
        "",
        "pub struct Theme {",
        "    pub id: &'static str,",
        "    pub name: &'static str,",
        "    pub accent: &'static str,",
        "    pub fonts: ThemeFonts,",
        "    pub dark: ThemeMode,",
        "    pub light: ThemeMode,",
        "}",
        "",
        "pub const THEMES: &[Theme] = &[",
    ]

    for theme_id, theme in themes.items():
        tf = get_fonts(fonts, theme_id)
        lines.append("    Theme {")
        lines.append(f"        id: {rust_str(theme_id)},")
        lines.append(f"        name: {rust_str(theme['name'])},")
        lines.append(f"        accent: {rust_str(theme['accent'])},")
        lines.append("        fonts: ThemeFonts {")
        lines.append(f"            heading: {rust_str(tf['heading'])},")
        lines.append(f"            body: {rust_str(tf['body'])},")
        lines.append(f"            mono_heading: {rust_str(tf['monoHeading'])},")
        lines.append(f"            mono_body: {rust_str(tf['monoBody'])},")
        lines.append("        },")
        for mode_name in ("dark", "light"):
            m = theme[mode_name]
            lines.append(f"        {mode_name}: ThemeMode {{")
            lines.append(f"            bg: {rust_str(m['bg'])},")
            lines.append(f"            surface: {rust_str(m['surface'])},")
            lines.append(f"            surface_alt: {rust_str(m['surfaceAlt'])},")
            lines.append(f"            accent: {rust_str(m['accent'])},")
            lines.append(f"            accent_soft: {rust_str(m['accentSoft'])},")
            lines.append(f"            text: {rust_str(m['text'])},")
            lines.append(f"            text_muted: {rust_str(m['textMuted'])},")
            lines.append(f"            border: {rust_str(m['border'])},")
            lines.append(f"            gradient: {rust_str(m['gradient'])},")
            lines.append("        },")
        lines.append("    },")

    lines.append("];")
    lines.append("")
    lines.append(f"pub const DEFAULT_THEME: &str = {rust_str(default_theme)};")
    lines.append("")
    lines.append("pub fn find_theme(id: &str) -> Option<&'static Theme> {")
    lines.append("    THEMES.iter().find(|t| t.id == id)")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    if not THEMES_JSON.is_file():
        print(f"Error: {THEMES_JSON} not found", file=sys.stderr)
        sys.exit(1)

    if not STATUS_JSON.is_file():
        print(f"Error: {STATUS_JSON} not found", file=sys.stderr)
        sys.exit(1)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    data = json.loads(THEMES_JSON.read_text())
    status = json.loads(STATUS_JSON.read_text())

    default_theme = data["defaultTheme"]
    themes = data["themes"]
    fonts = data.get("fonts", {})

    # Generate CSS
    css_out = OUT_DIR / "adi-theme.css"
    css_out.write_text(generate_css(themes, default_theme, fonts, status))
    print(f"  ✓ {css_out}")

    # Generate Rust
    rs_out = OUT_DIR / "themes.rs"
    rs_out.write_text(generate_rust(themes, default_theme, fonts))
    print(f"  ✓ {rs_out}")

    print(f"\nSync complete — {len(themes)} themes generated.")


if __name__ == "__main__":
    main()
